version: "3.9"
services:
    db:
        image: postgres
        restart: always
        environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASS}
            PGDATA: /var/lib/postgresql/data/pgdata
        ports:
            - "5435:5432"
        volumes:
            # Persistent data
            - ./coneg-postgres-data:/var/lib/postgresql/data
            # SQL to create/init ConEg tables
            - ./coneg-sql/initial_states.sql:/docker-entrypoint-initdb.d/initial_states.sql
    api:
        build: ./coneg-panel-api
        ports:
            - "5000:5000"
        depends_on:
            - db
        volumes:
            - ./data-backend:/coneg_root/shr-data
    api_inspector:
        build: ./coneg-insp-api
        ports:
            - "6000:6000"
        depends_on:
            - "api"
        volumes:
            - ./data-backend:/coneg_inspetint/shr-data
    web:
        build: ./coneg-panel
        ports:
            - "8080:8080"
        depends_on:
            - "api"